In [1]:
import torch
import torch.nn as nn
import math

# Demos

## Input embedding

In [14]:
# Embedding demo
from transformer_model import InputEmbedding
emb = InputEmbedding(512,10)
emb.forward(torch.tensor([1,2]))

tensor([[-12.0497, -18.7371,  14.3298,  ...,  39.7045,  -4.7265,  -1.6066],
        [  3.2736,  42.7494,  14.3427,  ..., -20.1249,  19.0128,  31.5516]],
       grad_fn=<MulBackward0>)

## Positional encoding

In [1]:
from transformer_model import PositionalEncoding
pe = PositionalEncoding(8,10,0.1) #Works if d_model is even
pe.pe

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
           1.0000e+00,  0.0000e+00,  1.0000e+00]],

        [[ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
           9.9995e-01,  1.0000e-03,  1.0000e+00]],

        [[ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
           9.9980e-01,  2.0000e-03,  1.0000e+00]],

        [[ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
           9.9955e-01,  3.0000e-03,  1.0000e+00]],

        [[-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
           9.9920e-01,  4.0000e-03,  9.9999e-01]],

        [[-9.5892e-01,  2.8366e-01,  4.7943e-01,  8.7758e-01,  4.9979e-02,
           9.9875e-01,  5.0000e-03,  9.9999e-01]],

        [[-2.7942e-01,  9.6017e-01,  5.6464e-01,  8.2534e-01,  5.9964e-02,
           9.9820e-01,  6.0000e-03,  9.9998e-01]],

        [[ 6.5699e-01,  7.5390e-01,  6.4422e-01,  7.6484e-01,  6.9943e-02,
           9.9755e-01,  6.9999e-03, 

## Layer Normalization

In [4]:
import torch
from transformer_model import LayerNormalization
ln = LayerNormalization()
ln(torch.tensor([0,2],dtype=torch.float32))

tensor([1.]) tensor([1.4142])


tensor([-0.7071,  0.7071], grad_fn=<AddBackward0>)

In [14]:
torch.ones(2,2).view(-1,2
                     )

tensor([[1., 1.],
        [1., 1.]])